type Subject = {
    rate: number;
    name: string;
};

export const calcMinRate = (subjects: Subject[]) => {
    return subjects.length > 0
        ? Math.min(...subjects.map((subject) => subject.rate))
        : "-";
};

export const makeSubjectNames = (subjects: Subject[]) => {
    return subjects.map((subject) => subject.name).join(", ");
}

export const subjects = [
    {
        title: "O & N Level",
        items: [
            "English",
            "Mother Tongue",
            "H. Mother Tongue",
            "Mother Tongue B",
            "Third Language",
            "E. Maths",
            "A. Maths",
            "POA",
            "P. Biology",
            "P. Physics",
            "P. Chemistry",
            "CS (Chem/Bio)",
            "CS (Chem/Phy)",
            "CS (Bio/Phy)",
            "P. Literature",
            "P. Geography",
            "P. History",
            "CH (SS/Lit)",
            "CH (SS/His)",
            "CH (SS/Lit in MT)",
            "D&T",
            "F&N",
            "Art",
            "Music",
            "H. Art",
            "H. Music",
            "Drama",
            "Computing",
            "Electronics",
        ],
    },
    {
        title: "PSLE",
        items: [
            "English",
            "Mother Tongue",
            "H. Mother Tongue",
            "Maths",
            "Science",
            "Social Studies",
        ],
    },
];

export const locationList = [
    "NORTH",
    "NORTH_WEST",
    "WEST",
    "CENTRAL",
    "NORTH_EAST",
    "EAST",
    "SOUTH",
];


export const availabilityList = [
    "MON:09",
    "MON:10",
    "MON:11",
    "MON:12",
    "MON:13",
    "MON:14",
    "MON:15",
    "MON:16",
    "MON:17",
    "MON:18",
    "MON:19",
    "MON:20",
    "TUE:09",
    "TUE:10",
    "TUE:11",
    "TUE:12",
    "TUE:13",
    "TUE:14",
    "TUE:15",
    "TUE:16",
    "TUE:17",
    "TUE:18",
    "TUE:19",
    "TUE:20",
    "WED:09",
    "WED:10",
    "WED:11",
    "WED:12",
    "WED:13",
    "WED:14",
    "WED:15",
    "WED:16",
    "WED:17",
    "WED:18",
    "WED:19",
    "WED:20",
    "THU:09",
    "THU:10",
    "THU:11",
    "THU:12",
    "THU:13",
    "THU:14",
    "THU:15",
    "THU:16",
    "THU:17",
    "THU:18",
    "THU:19",
    "THU:20",
    "FRI:09",
    "FRI:10",
    "FRI:11",
    "FRI:12",
    "FRI:13",
    "FRI:14",
    "FRI:15",
    "FRI:16",
    "FRI:17",
    "FRI:18",
    "FRI:19",
    "FRI:20",
    "SAT:09",
    "SAT:10",
    "SAT:11",
    "SAT:12",
    "SAT:13",
    "SAT:14",
    "SAT:15",
    "SAT:16",
    "SAT:17",
    "SAT:18",
    "SAT:19",
    "SAT:20",
    "SUN:09",
    "SUN:10",
    "SUN:11",
    "SUN:12",
    "SUN:13",
    "SUN:14",
    "SUN:15",
    "SUN:16",
    "SUN:17",
    "SUN:18",
    "SUN:19",
    "SUN:20",
];

export const displayList = ["OK"];